//! Configuration file handling.
//!
//! Config lives at `~/.config/tor-js-gateway/config.json5`.
//! Data lives at `~/.local/share/tor-js-gateway/`.

use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

const APP_NAME: &str = "tor-js-gateway";

/// Resolved paths for config and data directories.
pub fn config_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("~/.config"))
        .join(APP_NAME)
        .join("config.json5")
}

pub fn default_data_dir() -> PathBuf {
    dirs::data_local_dir()
        .unwrap_or_else(|| PathBuf::from("~/.local/share"))
        .join(APP_NAME)
}

fn default_key_file() -> PathBuf {
    default_data_dir().join("kps.key")
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Directory for cached consensus data and bootstrap archives
    pub data_dir: PathBuf,

    /// UDP port the KPS listener binds (serves both QUIC and WebRTC)
    pub kps_port: u16,

    /// Path to the persistent KPS identity key (PEM; created by `init`)
    pub kps_key_file: PathBuf,

    /// Directory of hash-named worker bundles (`<keccak256-hex>.js`), served
    /// at `/keccak/{hash[0..2]}/{hash[2..]}`; empty disables the
    /// worker-bundles capability
    pub worker_bundles_dir: PathBuf,

    /// IP addresses to advertise in metadata.json (the UDP port and certhash
    /// are appended automatically); empty auto-detects
    pub advertised_addresses: Vec<String>,

    /// Max concurrent CONNECT tunnels
    pub tunnel_max: usize,

    /// Max concurrent CONNECT tunnels per client IP (also the per-KPS-connection cap)
    pub tunnel_per_ip: usize,

    /// Tunnel idle timeout in seconds
    pub tunnel_idle_timeout: u64,

    /// Tunnel max lifetime in seconds
    pub tunnel_max_lifetime: u64,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            data_dir: default_data_dir(),
            kps_port: 42298,
            kps_key_file: default_key_file(),
            worker_bundles_dir: PathBuf::new(),
            advertised_addresses: Vec::new(),
            tunnel_max: 8192,
            tunnel_per_ip: 16,
            tunnel_idle_timeout: 300,
            tunnel_max_lifetime: 3600,
        }
    }
}

impl Config {
    /// Serialize to pretty JSON5 with comments.
    pub fn to_json5_with_comments() -> String {
        let cfg = Self::default();
        format!(
            r#"{{
  // Directory for cached consensus data and bootstrap archives
  "data_dir": {},

  // UDP port for the KPS listener — both QUIC and WebRTC ride this one port
  "kps_port": {},

  // Persistent KPS identity key (PEM). Generated by `init`; the certhash in
  // the gateway's published address is derived from it, so keep it stable.
  "kps_key_file": {},

  // Directory of worker bundles named <keccak256-hex>.js, served at
  // /keccak/{{hash[0..2]}}/{{hash[2..]}}. Empty string disables the
  // worker-bundles capability.
  "worker_bundles_dir": "",

  // IP addresses to advertise in metadata.json (the UDP port and certhash are
  // appended automatically). Empty: auto-detect from the default route.
  // Operators behind NAT must set this to their public IP(s).
  "advertised_addresses": [],

  // Max concurrent CONNECT tunnels
  "tunnel_max": {},

  // Max concurrent CONNECT tunnels per client IP (also caps tunnels per KPS connection)
  "tunnel_per_ip": {},

  // Tunnel idle timeout in seconds
  "tunnel_idle_timeout": {},

  // Tunnel max lifetime in seconds
  "tunnel_max_lifetime": {},
}}"#,
            serde_json::to_string(&cfg.data_dir).unwrap(),
            cfg.kps_port,
            serde_json::to_string(&cfg.kps_key_file).unwrap(),
            cfg.tunnel_max,
            cfg.tunnel_per_ip,
            cfg.tunnel_idle_timeout,
            cfg.tunnel_max_lifetime,
        )
    }

    /// Load config from the given path.
    pub fn load(path: &PathBuf) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading config at {}\n\nRun `tor-js-gateway init` to create a default config.", path.display()))?;
        let cfg: Config =
            json5::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
        Ok(cfg)
    }

    /// Create the default config file. Errors if it already exists.
    pub fn init(path: &PathBuf) -> Result<()> {
        if path.exists() {
            anyhow::bail!("config already exists at {}", path.display());
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        let content = Self::to_json5_with_comments();
        std::fs::write(&path, &content)
            .with_context(|| format!("writing {}", path.display()))?;
        println!("Created config at {}", path.display());
        Ok(())
    }
}
